### ISSUE TITLE
Instagram shows "Couldn't load media"

### ISSUE THREAD

**Issue by iAdam1n** [hbang/LinkOpener#24]
https://instagram.com/p/-P4nfkhXWt/

![image1](https://cloud.githubusercontent.com/assets/2139641/11277638/411d605a-8edf-11e5-86f2-4cfd72b71279.PNG)

**Comment by tmnlsthrn** [comment]
It seems `instagram://media?id=C` is not working any longer, requires more investigation.

**Comment by tmnlsthrn** [comment]
Instagram is now(?) using numeric id's for linking to posts with the `instagram` url schemes.

`instagram://media?id=C` is now `instagram://media?id=2`?
Weird, because [instagram.com/p/2/](instagram.com/p/2/) is a totally different picture.
